### ISSUE TITLE
Training transmitter stuck in infinite loop

### ISSUE THREAD

**Issue by tungnt55** [SivilTaram/Persona-Dialogue-Generation#16]
I was trying to train a transmitter following the instruction in the main page.  
During training, the training script runs to run_eval(). Here it seems to run forever and stucks in an infinite loop.

**Comment by SivilTaram** [comment]
@tungnt55 In fact, evaluating will cost a lot more than training since it will employ beam search to generate the best response and calculating the metrics (I remembered Hits@K costs the most). Please stay patient and keep it running. If you wanna to save time on evaluation, I will recommend to (i) create a relatively small dev set to evaluate; (ii) disable the Hits@K calculation on development.

**Comment by tungnt55** [comment]
Thank you for the reply. Now I can confirm that everything is working as expected.
