### ISSUE TITLE
psquare model is not saved after running `train_psquare.py`

### ISSUE THREAD

**Issue by OneDirection9** [SivilTaram/Persona-Dialogue-Generation#17]
Hi,
 great work and thanks for sharing.

  When I run `train_transmitter.py`, `train_receiver_model.py`, and `train_psquare.py` step by step. I can get the transmitter and receiver model, except the `psquare` model. I go through the code and can't fix it by myself. Can you help?

Thanks.

**Comment by SivilTaram** [comment]
@OneDirection9 
Hi, thanks for your interests on our work. Please find there is any output log matching the pattern `Save model at` and you could find the psqure model checkpoint there.

**Comment by OneDirection9** [comment]
Hi @SivilTaram ,

  Thanks for your reply.
  The default save directory is `tmp`, I can find the `transmitter` and `receiver` model under there. But in the `psquare` folder, there is only a `tensorboard` folder.

**Comment by SivilTaram** [comment]
@OneDirection9 Hi, thanks for your feedback! Since I just checked evaluation scripts carefully before releasing the code (the model weights are the ones saved before submitting the paper to ACL), so it is possible that the current code is not totally compatible with the provided ParlAI version. And I will try to reproduce the result as soon as possible and get back here in 2 days. Please stay tuned ☕

**Comment by SivilTaram** [comment]
@OneDirection9 Hi~ Many thanks for your feedback. Yeah it is indeed an issue for our code (sorry for that). And it could work well now, and pls have a try ☕
