### ISSUE TITLE
What is "PSquare"

### ISSUE THREAD

**Issue by Wenze7** [SivilTaram/Persona-Dialogue-Generation#37]
Hi! I'm glad to see your great work. 
Could you tell me what is "PSquare", I don't find it in paper.
And, the project consist of too many files, it's so hard for me to figure out the logic of the project, so could you provide a more specific doc.
Best!

**Comment by SivilTaram** [comment]
@Wenze7 Hi, PSquare is the P^2 Bot optimized by our proposed reinforcement learning algorithm. Regarding to the doc specification, sorry for that because of the complexity of ParlAI. If you want to figure out how the code works, you may refer to [their codebase](https://parl.ai/) for more documents.
